/**
 * Supported cities for collection points (must match backend allowlist).
 * Keep in sync with Backend/src/constants/collectionPointCities.js
 */
export const COLLECTION_POINT_CITIES = [
  'Ampara',
  'Anuradhapura',
  'Badulla',
  'Balangoda',
  'Bandarawela',
  'Batticaloa',
  'Beruwala',
  'Chilaw',
  'Colombo',
  'Dambulla',
  'Dehiwala-Mount Lavinia',
  'Elpitiya',
  'Galle',
  'Gampaha',
  'Gampola',
  'Hambantota',
  'Hatton',
  'Homagama',
  'Horana',
  'Ja-Ela',
  'Jaffna',
  'Kadawatha',
  'Kaduwela',
  'Kalutara',
  'Kandana',
  'Kandy',
  'Katunayake',
  'Kelaniya',
  'Kegalle',
  'Kesbewa',
  'Kilinochchi',
  'Kiribathgoda',
  'Kolonnawa',
  'Kuliyapitiya',
  'Kurunegala',
  'Maharagama',
  'Malabe',
  'Mannar',
  'Matale',
  'Matara',
  'Minuwangoda',
  'Monaragala',
  'Moratuwa',
  'Mullaitivu',
  'Negombo',
  'Nugegoda',
  'Nuwara Eliya',
  'Panadura',
  'Pelmadulla',
  'Point Pedro',
  'Polonnaruwa',
  'Puttalam',
  'Ratmalana',
  'Ratnapura',
  'Tangalle',
  'Trincomalee',
  'Vavuniya',
  'Wadduwa',
  'Wattala',
  'Weligama',
] as const;

export type CollectionPointCity = (typeof COLLECTION_POINT_CITIES)[number];
